version: "2"
services:
  master:
    image: eeacms/jenkins-master
    privileged: true
    ports:
    - "8080:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

  worker:
    image: eeacms/jenkins-slave
    privileged: true
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "admin"
      JENKINS_PASS: "admin"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-master:
  jenkins-worker: